{{- if eq (toString .Values.management.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: stratify
  namespace: {{.Release.Name}}
  labels:
    app: stratify
    
spec:
  selector:
    app: stratify
  ports:
    - name: management
      port: {{ .Values.management.port }}
      targetPort: 8000
  type: LoadBalancer
{{- end }}